name: django-test

on:
  pull_request:
    branches:
      - stage
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: install dependencies
      run:
        python -m pip install
        pip install django typing_extensions sqlparse asgiref psycopg
        

    - name: python-django
      run: |
         python manage.py
