name: Python CI/CD PIPELINE branch

on:
  workflow_dispatch:
  

jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
    - uses: actions/checkout@v2
    - name: setup python 3.11.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4
    - name: install dependencies
      run:
        python -m pip install
        pip install django typing_extensions sqlparse asgiref psycopg pycodestyle
      - name: Check Syntax 
        run: pycodestyle --statistics .

      - name: Run Test # running tests
        run: python manage.py test

    - name: python-django
      run: |
         python manage.py

  STAGING:
    runs-on: ubuntu-latest
    environment: STAGING
    needs: DEV

    steps:
    - uses: actions/checkout@v2
    - name: setup python 3.11.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4
    - name: install dependencies
      run:
        python -m pip install
        pip install django typing_extensions sqlparse asgiref psycopg pycodestyle
      - name: Check Syntax # check code formatting
        run: pycodestyle --statistics .

      - name: Run Test # running tests
        run: python manage.py test

    - name: python-django
      run: |
         python manage.py

  PRODUCTION:
    runs-on: ubuntu-latest
    environment: PRODUCTION
    needs: STAGING

    steps:
    - uses: actions/checkout@v2
    - name: setup python 3.11.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4
    - name: install dependencies
      run:
        python -m pip install
        pip install django typing_extensions sqlparse asgiref psycopg pycodestyle
      - name: Check Syntax # check code formatting
        run: pycodestyle --statistics .

      - name: Run Test # running tests
        run: python manage.py test

    - name: python-django
      run: |
         python manage.py
