  name: Python CI/CD PIPELINE branch

on:
  push:
    branches:
      - DEV
  workflow_dispatch:
  

jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
    - uses: actions/checkout@v2
    - name: setup python 3.11.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4
    - name: install dependencies
      run:
        python -m pip install
        pip install django typing_extensions sqlparse asgiref psycopg

    - name: python-django
      run: |
         python manage.py

on:
  pull:
    branches:
      - STAGING
  workflow_dispatch:
  

jobs:
  STAGING:
    runs-on: ubuntu-latest
    environment: STAGING
    needs: DEV

    steps:
    - uses: actions/checkout@v2
    - name: setup python 3.11.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4
    - name: install dependencies
      run:
        python -m pip install
        pip install django typing_extensions sqlparse asgiref psycopg

    - name: python-django
      run: |
         python manage.py
