name: Python CI/CD dev branch

on:
  push:
    branches:
      - main
  workflow_dispatch:
  

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: install dependencies
      run:
        python -m pip install
        pip install django typing_extensions sqlparse asgiref psycopg
    - name: python-django
      run: |
         python manage.py
